#!/usr/bin/env bash

basedir=$(dirname "$0")
export STEMCELL_DEPS_DIR="$(pwd)/windows-stemcell-dependencies"
export PACKER_LOG=10

pushd bosh-windows-stemcell-builder

gem install bundler --no-document
bundle install

popd

# Packer
curl -L -O -J https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip
unzip packer*.zip
rm packer*.zip

# jetbrains packer vsphere 1.3.1.dev1
curl -L -O -J https://s3-eu-west-1.amazonaws.com/windows2012-stemcells/dependencies/packer-builder-vsphere.linux

chmod +x packer*
cp packer* /usr/local/bin/

curl -L -O -J https://s3-eu-west-1.amazonaws.com/windows2012-stemcells/dependencies/VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle
chmod +x VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle
./VMware-ovftool-4.2.0-5965791-lin.x86_64.bundle --eulas-agreed --required

# LGPO
curl -L -O -J https://msdnshared.blob.core.windows.net/media/2016/09/LGPOv2-PRE-RELEASE.zip
unzip LGPO*.zip

mkdir -p ${STEMCELL_DEPS_DIR}/lgpo
mv LGPO.exe ${STEMCELL_DEPS_DIR}/lgpo/

# stembuild
curl -L -O -J https://github.com/pivotal-cf-experimental/stembuild/releases/download/0.7/stembuild_linux_amd64
chmod +x stembuild*
mv stembuild* /usr/local/bin/stembuild

mkdir -p scripts
cp -R bosh-windows-stemcell-builder/scripts/* scripts/

mkdir -p ../sshd
curl -L -O -J https://github.com/PowerShell/Win32-OpenSSH/releases/download/v0.0.18.0/OpenSSH-Win64.zip
mv OpenSSH-Win64.zip ../sshd/

ruby ci/tasks/create-vsphere-stemcell/create-vsphere-stemcell.rb "$(pwd)/bosh-windows-stemcell-builder/lib"

#GOVC
curl -L -O -J https://github.com/vmware/govmomi/releases/download/v0.15.0/govc_linux_amd64.gz
gunzip govc*
chmod +x govc*
cp govc* /usr/local/bin/govc

export GOVC_URL=$VCENTER_SERVER
export GOVC_USERNAME=$VCENTER_USERNAME
export GOVC_PASSWORD=$VCENTER_PASSWORD
export GOVC_INSECURE=true
echo "removing temp stemcell vm"
govc vm.destroy packer-vmx

# see https://github.com/pivotal-cf-experimental/stembuild/issues/2
echo "moving stemcel this can take a while"
mv /root/packer-vmx/bosh-stemcell-*.tgz stemcell/
echo "moving stemcell done"
